# Base infrastructure components (databases and storage)
# This file contains essential services that other Camunda Platform components depend on

services:
  elasticsearch: # https://hub.docker.com/_/elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_DB_PASSWORD}
      # allow running with low disk space
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - ./container.elasticsearch/data:/usr/share/elasticsearch/data
      - ./container.elasticsearch/docker-entrypoint.d/entrypoint.sh:/entrypoint.sh

    command: ["/entrypoint.sh"]
    networks:
      - camunda-platform
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f -u elastic:$${ELASTIC_PASSWORD} http://localhost:9200/_cat/health | grep -q green",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: "2.0"
        reservations:
          memory: 3G
          cpus: "1.0"

  postgres: # https://hub.docker.com/_/postgres
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      TZ: ${TIMEZONE}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./container.postgres/data:/var/lib/postgresql/data
    networks:
      - identity-network
      - camunda-platform
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"

networks:
  camunda-platform:
  identity-network:
