# Core Camunda Services
# This file contains essential orchestration components

services:
  zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
    image: camunda/zeebe:${CAMUNDA_ZEEBE_VERSION}
    container_name: zeebe
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zeebe-grpc.rule=Host(`zeebe.${HOSTNAME}`)"
      - "traefik.http.routers.zeebe-grpc.entrypoints=webgrpc"
      - "traefik.http.routers.zeebe-grpc.tls.certresolver=letsencrypt"
      - "traefik.http.services.zeebe-grpc.loadbalancer.server.port=26500"
      - "traefik.http.routers.zeebe-grpc.tls=true"
      - "traefik.http.routers.zeebe-grpc.service=zeebe-grpc"
    environment: # https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_MODE=${ZEEBE_AUTHENTICATION_MODE}
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL=http://keycloak:18080/auth/realms/camunda-platform
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_AUDIENCE=zeebe-api
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_BASEURL=http://identity:8084
      - ZEEBE_BROKER_GATEWAY_MULTITENANCY_ENABLED=${MULTI_TENANCY_ENABLED}
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_USERNAME=elastic
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_PASSWORD=${ELASTIC_DB_PASSWORD}
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - CAMUNDA_IDENTITY_ISSUERBACKENDURL=http://keycloak:18080/auth/realms/camunda-platform
      - CAMUNDA_IDENTITY_BASEURL=http://identity:8084
      - CAMUNDA_IDENTITY_AUDIENCE=zeebe-api
      - SPRING_PROFILES_ACTIVE=identity-auth
      - "JAVA_TOOL_OPTIONS=-Xms1g -Xmx1g"
      - management.endpoints.web.exposure.include=health,info,metrics,prometheus,configprops
      - MANAGEMENT_ENDPOINT_CONFIGPROPS_SHOW_VALUES=ALWAYS
    env_file:
      - path: ./configuration/runtime.env
        required: true
    volumes:
      - ./container.zeebe/data:/usr/local/zeebe/data
    networks:
      - camunda-platform
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      elasticsearch:
        condition: service_healthy
      identity:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "1"
        reservations:
          memory: 2G
          cpus: "0.8"

  operate: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#operate
    image: camunda/operate:${CAMUNDA_OPERATE_VERSION}
    container_name: operate
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.operate.rule=Host(`${HOSTNAME}`) && PathPrefix(`/operate`)"
      - "traefik.http.routers.operate.entrypoints=websecure"
      - "traefik.http.routers.operate.tls.certresolver=letsencrypt"
      - "traefik.http.services.operate.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.operate-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.operate-headers.headers.customrequestheaders.X-Forwarded-Host=${HOSTNAME}"
      - "traefik.http.middlewares.operate-headers.headers.customrequestheaders.X-Forwarded-For=$${client_ip}"
      - "traefik.http.middlewares.operate-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.operate-cors.headers.accesscontrolallowmethods=${CORS_ALLOWED_METHODS}"
      - "traefik.http.middlewares.operate-cors.headers.accesscontrolallowheaders=${CORS_ALLOWED_HEADERS}"
      - "traefik.http.middlewares.operate-cors.headers.accesscontrolalloworiginlist=${CORS_ALLOWED_ORIGINS}"
      - "traefik.http.middlewares.operate-cors.headers.accesscontrolallowcredentials=${CORS_ALLOW_CREDENTIALS}"
      - "traefik.http.routers.operate.middlewares=operate-headers,operate-cors"
    environment: #https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/
      - SERVER_SERVLET_CONTEXT_PATH=/operate
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - ZEEBE_CLIENT_ID=${ZEEBE_CLIENT_ID}
      - ZEEBE_CLIENT_SECRET=${ZEEBE_CLIENT_SECRET}
      - ZEEBE_TOKEN_AUDIENCE=zeebe-api
      - ZEEBE_AUTHORIZATION_SERVER_URL=http://keycloak:18080/auth/realms/camunda-platform/protocol/openid-connect/token
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ELASTICSEARCH_USERNAME=elastic
      - CAMUNDA_OPERATE_ELASTICSEARCH_PASSWORD=${ELASTIC_DB_PASSWORD}
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_USERNAME=elastic
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PASSWORD=${ELASTIC_DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=identity-auth
      - CAMUNDA_OPERATE_IDENTITY_BASEURL=http://identity:8084
      - CAMUNDA_OPERATE_IDENTITY_ISSUER_URL=https://${HOSTNAME}/auth/realms/camunda-platform
      - CAMUNDA_OPERATE_IDENTITY_ISSUER_BACKEND_URL=http://keycloak:18080/auth/realms/camunda-platform
      - CAMUNDA_OPERATE_IDENTITY_CLIENTID=operate
      - CAMUNDA_OPERATE_IDENTITY_CLIENTSECRET=${OPERATE_CLIENT_SECRET}
      - SERVER_FORWARD_HEADERS_STRATEGY=native
      - CAMUNDA_OPERATE_IDENTITY_AUDIENCE=operate-api
      - CAMUNDA_OPERATE_MULTITENANCY_ENABLED=${MULTI_TENANCY_ENABLED}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:18080/auth/realms/camunda-platform
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:18080/auth/realms/camunda-platform/protocol/openid-connect/certs
      - CAMUNDA_OPERATE_IDENTITY_RESOURCEPERMISSIONSENABLED=${RESOURCE_AUTHORIZATIONS_ENABLED}
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - management.endpoints.web.exposure.include=health,info,metrics,prometheus,configprops
      - MANAGEMENT_ENDPOINT_CONFIGPROPS_SHOW_VALUES=ALWAYS
      - management.endpoint.health.probes.enabled=true
      - ZEEBE_CLIENT_CONFIG_PATH=/tmp/zeebe_auth_cache
    volumes:
      - ./container.operate/tmp:/tmp
    networks:
      - camunda-platform
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O - -q 'http://localhost:9600/actuator/health/readiness'",
        ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    depends_on:
      zeebe:
        condition: service_healthy
      identity:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 200M
          cpus: "0.3"

  tasklist: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#tasklist
    image: camunda/tasklist:${CAMUNDA_TASKLIST_VERSION}
    container_name: tasklist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tasklist.rule=Host(`${HOSTNAME}`) && PathPrefix(`/tasklist`)"
      - "traefik.http.routers.tasklist.entrypoints=websecure"
      - "traefik.http.routers.tasklist.tls.certresolver=letsencrypt"
      - "traefik.http.services.tasklist.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.tasklist-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.tasklist-headers.headers.customrequestheaders.X-Forwarded-Host=${HOSTNAME}"
      - "traefik.http.middlewares.tasklist-headers.headers.customrequestheaders.X-Forwarded-For=$${client_ip}"
      - "traefik.http.middlewares.tasklist-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.tasklist-cors.headers.accesscontrolallowmethods=${CORS_ALLOWED_METHODS}"
      - "traefik.http.middlewares.tasklist-cors.headers.accesscontrolallowheaders=${CORS_ALLOWED_HEADERS}"
      - "traefik.http.middlewares.tasklist-cors.headers.accesscontrolalloworiginlist=${CORS_ALLOWED_ORIGINS}"
      - "traefik.http.middlewares.tasklist-cors.headers.accesscontrolallowcredentials=${CORS_ALLOW_CREDENTIALS}"
      - "traefik.http.routers.tasklist.middlewares=tasklist-headers,tasklist-cors"
    environment: # https://docs.camunda.io/docs/self-managed/tasklist-deployment/tasklist-configuration/
      - SERVER_SERVLET_CONTEXT_PATH=/tasklist
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS=http://zeebe:8080
      - ZEEBE_CLIENT_ID=${ZEEBE_CLIENT_ID}
      - ZEEBE_CLIENT_SECRET=${ZEEBE_CLIENT_SECRET}
      - ZEEBE_CLIENT_CONFIG_PATH=/tmp/zeebe_auth_cache
      - ZEEBE_TOKEN_AUDIENCE=zeebe-api
      - ZEEBE_AUTHORIZATION_SERVER_URL=http://keycloak:18080/auth/realms/camunda-platform/protocol/openid-connect/token
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ELASTICSEARCH_USERNAME=elastic
      - CAMUNDA_TASKLIST_ELASTICSEARCH_PASSWORD=${ELASTIC_DB_PASSWORD}
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_USERNAME=elastic
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_PASSWORD=${ELASTIC_DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=identity-auth
      - CAMUNDA_TASKLIST_IDENTITY_BASEURL=http://identity:8084
      - CAMUNDA_TASKLIST_IDENTITY_ISSUER_URL=https://${HOSTNAME}/auth/realms/camunda-platform
      - CAMUNDA_TASKLIST_IDENTITY_ISSUER_BACKEND_URL=http://keycloak:18080/auth/realms/camunda-platform
      - CAMUNDA_TASKLIST_IDENTITY_CLIENTID=tasklist
      - CAMUNDA_TASKLIST_IDENTITY_CLIENTSECRET=${TASKLIST_CLIENT_SECRET}
      - SERVER_FORWARD_HEADERS_STRATEGY=native
      - CAMUNDA_TASKLIST_IDENTITY_AUDIENCE=tasklist-api
      - CAMUNDA_TASKLIST_MULTITENANCY_ENABLED=${MULTI_TENANCY_ENABLED}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:18080/auth/realms/camunda-platform
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:18080/auth/realms/camunda-platform/protocol/openid-connect/certs
      - CAMUNDA_TASKLIST_IDENTITY_RESOURCE_PERMISSIONS_ENABLED=${RESOURCE_AUTHORIZATIONS_ENABLED}
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - management.endpoints.web.exposure.include=health,info,metrics,prometheus,configprops
      - MANAGEMENT_ENDPOINT_CONFIGPROPS_SHOW_VALUES=ALWAYS
      - management.endpoint.health.probes.enabled=true
    env_file:
      - path: ./configuration/runtime.env
        required: true
    volumes:
      - ./container.tasklist/tmp:/tmp
    networks:
      - camunda-platform
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -O - -q 'http://localhost:9600/actuator/health/readiness'",
        ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    depends_on:
      zeebe:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      identity:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 200M
          cpus: "0.3"

  connectors: # https://docs.camunda.io/docs/self-managed/setup/deploy/other/docker/#Connectors
    image: camunda/connectors-bundle:${CAMUNDA_CONNECTORS_VERSION}
    container_name: connectors
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.connectors.rule=Host(`${HOSTNAME}`) && PathPrefix(`/connectors`)"
      - "traefik.http.routers.connectors.entrypoints=websecure"
      - "traefik.http.routers.connectors.tls.certresolver=letsencrypt"
      - "traefik.http.services.connectors.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.connectors-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.connectors-headers.headers.customrequestheaders.X-Forwarded-Host=${HOSTNAME}"
      - "traefik.http.middlewares.connectors-cors.headers.accesscontrolallowmethods=${CORS_ALLOWED_METHODS}"
      - "traefik.http.middlewares.connectors-cors.headers.accesscontrolallowheaders=${CORS_ALLOWED_HEADERS}"
      - "traefik.http.middlewares.connectors-cors.headers.accesscontrolalloworiginlist=${CORS_ALLOWED_ORIGINS}"
      - "traefik.http.middlewares.connectors-cors.headers.accesscontrolallowcredentials=${CORS_ALLOW_CREDENTIALS}"
      - "traefik.http.routers.connectors.middlewares=connectors-headers,connectors-cors"
    environment: # https://docs.camunda.io/docs/self-managed/connectors-deployment/connectors-configuration/
      - OPERATE_CLIENT_BASEURL=http://operate:8080/operate
      - OPERATE_CLIENT_PROFILE=oidc
      - OPERATE_CLIENT_AUTHURL=http://keycloak:18080/auth/realms/camunda-platform/protocol/openid-connect/token
      - OPERATE_CLIENT_AUDIENCE=operate-api
      - OPERATE_CLIENT_CLIENTID=connectors
      - OPERATE_CLIENT_CLIENTSECRET=${CONNECTORS_CLIENT_SECRET}
      - CAMUNDA_CLIENT_MODE=self-managed
      - CAMUNDA_CLIENT_ZEEBE_GRPCADDRESS=http://zeebe:26500
      - CAMUNDA_CLIENT_ZEEBE_RESTADDRESS=http://zeebe:8080
      - CAMUNDA_CLIENT_AUTH_CLIENTID=${ZEEBE_CLIENT_ID}
      - CAMUNDA_CLIENT_AUTH_CLIENTSECRET=${ZEEBE_CLIENT_SECRET}
      - CAMUNDA_CLIENT_AUTH_TOKEN_URL=http://keycloak:18080/auth/realms/camunda-platform/protocol/openid-connect/token
      - CAMUNDA_CLIENT_ZEEBE_AUDIENCE=zeebe-api
      - CAMUNDA_IDENTITY_CLIENT_ID=connectors
      - CAMUNDA_IDENTITY_CLIENT_SECRET=${CONNECTORS_CLIENT_SECRET}
      - CAMUNDA_IDENTITY_TYPE=KEYCLOAK
      - CAMUNDA_IDENTITY_AUDIENCE=operate-api
      - ZEEBE_CLIENT_CONFIG_PATH=/tmp/zeebe_auth_cache
      - management.endpoints.web.exposure.include=health,info,metrics,prometheus,configprops
      - MANAGEMENT_ENDPOINT_CONFIGPROPS_SHOW_VALUES=ALWAYS
      - management.endpoint.health.probes.enabled=true
    env_file:
      - path: ./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/connector-secrets.txt
        required: true
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readiness"]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform
    depends_on:
      zeebe:
        condition: service_healthy
      operate:
        condition: service_healthy
      identity:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: "0.4"
        reservations:
          memory: 250M
          cpus: "0.2"

networks:
  camunda-platform:
