# Keycloak Connector Service
# This file deploys the PoC for User Creation on Keycloak

services:
  kc-connector:
    container_name: kc-connector
    build:
      context: ./kc-connector
      dockerfile: Dockerfile
    environment:
      TZ: ${TIMEZONE}
      HOSTNAME: ${HOSTNAME}
      KC_ADMIN_USER: ${KC_ADMIN_USER}
      KC_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    networks:
      - camunda-platform
      - identity-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      keycloak:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.2"

networks:
  camunda-platform:
  identity-network:
