services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${HOSTNAME}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD_HASH}"
    command:
      # Dashboard und healthcheck api
      - "--api.dashboard=${TRAEFIK_DASHBOARD_ENABLED}"
      - "--ping=true"
      # Logging
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--log.maxAge=1"
      - "--log.compress=true"
      - "--accesslog=true"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.webgrpc.address=:26500"
      # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=camunda-platform"
      # Default fallback rule
      - "--providers.docker.defaultrule=Host(`${HOSTNAME}`)"
      # Let's Encrypt configuration
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # Uncomment for testing (acme staging server)
      # - "--certificatesresolvers.letsencrypt.acme.caserver=${ACME_CASERVER}"
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "80:80"
      - "443:443"
      - "26500:26500"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./container.traefik/letsencrypt:/letsencrypt
    networks:
      - camunda-platform
      - identity-network
      - web-modeler
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: "0.5"
        reservations:
          memory: 300M
          cpus: "0.25"

networks:
  camunda-platform:
  identity-network:
  web-modeler:
