# Monitoring Components
# This file contains services for monitoring and logging

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`${TRAEFIK_HOSTNAME}`) && PathPrefix(`/kibana`)"
      - "traefik.http.routers.kibana.entrypoints=web"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
    volumes:
      - kibana:/usr/share/kibana/data
    networks:
      - camunda-platform
    depends_on:
      - elasticsearch

volumes:
  kibana:

networks:
  camunda-platform: 