# Optimize Service
# This file contains the Optimize component for advanced analytics

services:
  optimize: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#optimize
    image: camunda/optimize:${CAMUNDA_OPTIMIZE_VERSION}
    container_name: optimize
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 400M
          cpus: '0.3'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.optimize.rule=Host(`${HOSTNAME}`) && PathPrefix(`/optimize`)"
      - "traefik.http.routers.optimize.entrypoints=websecure"
      - "traefik.http.routers.optimize.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.optimize-stripprefix.stripprefix.prefixes=/optimize"
      - "traefik.http.services.optimize.loadbalancer.server.port=8090"
      - "traefik.http.middlewares.optimize-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.optimize-headers.headers.customrequestheaders.X-Forwarded-Host=${HOSTNAME}"
      - "traefik.http.middlewares.optimize-cors.headers.accesscontrolallowmethods=${CORS_ALLOWED_METHODS}"
      - "traefik.http.middlewares.optimize-cors.headers.accesscontrolallowheaders=${CORS_ALLOWED_HEADERS}"
      - "traefik.http.middlewares.optimize-cors.headers.accesscontrolalloworiginlist=${CORS_ALLOWED_ORIGINS}"
      - "traefik.http.middlewares.optimize-cors.headers.accesscontrolallowcredentials=${CORS_ALLOW_CREDENTIALS}"
      - "traefik.http.routers.optimize.middlewares=optimize-headers,optimize-stripprefix"
    environment:
      - CAMUNDA_OPTIMIZE_IDENTITY_REDIRECT_ROOT_URL=https://${HOSTNAME}/optimize
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=9200
      - SPRING_PROFILES_ACTIVE=ccsm
      - CAMUNDA_OPTIMIZE_ZEEBE_ENABLED=true
      - CAMUNDA_OPTIMIZE_ENTERPRISE=false
      - CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_URL=https://${HOSTNAME}/auth/realms/camunda-platform
      - CAMUNDA_OPTIMIZE_IDENTITY_ISSUER_BACKEND_URL=http://keycloak:18080/auth/realms/camunda-platform
      - CAMUNDA_OPTIMIZE_IDENTITY_CLIENTID=optimize
      - CAMUNDA_OPTIMIZE_IDENTITY_CLIENTSECRET=XALaRPl5qwTEItdwCMiPS62nVpKs7dL7
      - CAMUNDA_OPTIMIZE_IDENTITY_AUDIENCE=optimize-api
      - CAMUNDA_OPTIMIZE_IDENTITY_BASE_URL=http://identity:8084
      - CAMUNDA_OPTIMIZE_MULTITENANCY_ENABLED=${MULTI_TENANCY_ENABLED}
      - CAMUNDA_OPTIMIZE_SECURITY_AUTH_COOKIE_SAME_SITE_ENABLED=false
      - CAMUNDA_OPTIMIZE_UI_LOGOUT_HIDDEN=true
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090/api/readyz"]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    volumes:
      - "./.optimize/environment-config.yaml:/optimize/config/environment-config.yaml"
    restart: on-failure
    networks:
      - camunda-platform
    depends_on:
      - identity
      - elasticsearch

networks:
  camunda-platform: