# Web Modeler Components
# This file contains services for the Camunda Web Modeler

services:
  web-modeler-db:
    container_name: web-modeler-db
    image: postgres:${POSTGRES_VERSION}
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 500M
          cpus: '0.25'
    healthcheck:
      test: pg_isready -d web-modeler-db -U web-modeler-db-user
      interval: 5s
      timeout: 15s
      retries: 30
    environment:
      POSTGRES_DB: web-modeler-db
      POSTGRES_USER: web-modeler-db-user
      POSTGRES_PASSWORD: web-modeler-db-password
    networks:
      - web-modeler
      - camunda-platform
    volumes:
      - postgres-web:/var/lib/postgresql/data

  mailpit:
    # If you want to use your own SMTP server, you can remove this container
    # and configure RESTAPI_MAIL_HOST, RESTAPI_MAIL_PORT, REST_API_MAIL_USER,
    # REST_API_MAIL_PASSWORD and RESTAPI_MAIL_ENABLE_TLS in web-modeler-restapi
    container_name: mailpit
    image: axllent/mailpit:${MAILPIT_VERSION}
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '0.2'
        reservations:
          memory: 150M
          cpus: '0.1'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`${HOSTNAME}`) && PathPrefix(`/mail`)" # For Mailpit UI
      - "traefik.http.routers.mailpit.entrypoints=websecure"
      - "traefik.http.routers.mailpit.tls.certresolver=letsencrypt"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"
      - "traefik.http.middlewares.mailpit-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.mailpit-headers.headers.customrequestheaders.X-Forwarded-Host=${HOSTNAME}"
      - "traefik.http.routers.mailpit.middlewares=mailpit-headers"
    healthcheck:
      test: /usr/bin/nc -v localhost 1025
      interval: 30s
    networks:
      - web-modeler

  web-modeler-restapi:
    container_name: web-modeler-restapi
    image: camunda/web-modeler-restapi:${CAMUNDA_WEB_MODELER_VERSION}
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '0.8'
        reservations:
          memory: 800M
          cpus: '0.3'
    command: /bin/sh -c "java $JAVA_OPTIONS org.springframework.boot.loader.JarLauncher"
    depends_on:
      web-modeler-db:
        condition: service_healthy
      mailpit:
        condition: service_started
      identity:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8091/health/readiness"]
      interval: 5s
      timeout: 15s
      retries: 30
    environment:
      JAVA_OPTIONS: -Xmx128m
      LOGGING_LEVEL_IO_CAMUNDA_MODELER: DEBUG
      CAMUNDA_IDENTITY_BASEURL: https://${HOSTNAME}/identity/ # Updated for HTTPS
      SPRING_DATASOURCE_URL: jdbc:postgresql://web-modeler-db:5432/web-modeler-db
      SPRING_DATASOURCE_USERNAME: web-modeler-db-user
      SPRING_DATASOURCE_PASSWORD: web-modeler-db-password
      SPRING_PROFILES_INCLUDE: default-logging
      RESTAPI_PUSHER_HOST: web-modeler-websockets
      RESTAPI_PUSHER_PORT: "8060"
      RESTAPI_PUSHER_APP_ID: web-modeler-app
      RESTAPI_PUSHER_KEY: web-modeler-app-key
      RESTAPI_PUSHER_SECRET: web-modeler-app-secret
      RESTAPI_OAUTH2_TOKEN_ISSUER: https://${HOSTNAME}/auth/realms/camunda-platform # Updated for HTTPS
      RESTAPI_OAUTH2_TOKEN_ISSUER_BACKEND_URL: http://keycloak:18080/auth/realms/camunda-platform # Internal URL, remains unchanged
      RESTAPI_SERVER_URL: https://${HOSTNAME}/modeler # Updated for HTTPS
      RESTAPI_MAIL_HOST: mailpit
      RESTAPI_MAIL_PORT: 1025
      RESTAPI_MAIL_ENABLE_TLS: "false"
      RESTAPI_MAIL_FROM_ADDRESS: "noreply@example.com"
      CAMUNDA_MODELER_CLUSTERS_0_ID: "local-zeebe"
      CAMUNDA_MODELER_CLUSTERS_0_NAME: "Local Zeebe instance"
      CAMUNDA_MODELER_CLUSTERS_0_VERSION: ${CAMUNDA_ZEEBE_VERSION}
      CAMUNDA_MODELER_CLUSTERS_0_URL_ZEEBE_GRPC: grpc://zeebe.${HOSTNAME}:26500 # Updated for external gRPC access
      CAMUNDA_MODELER_CLUSTERS_0_URL_ZEEBE_REST: https://${HOSTNAME}/zeebe # Updated for REST API via Traefik
      CAMUNDA_MODELER_CLUSTERS_0_URL_OPERATE: https://${HOSTNAME}/operate # Updated for HTTPS
      CAMUNDA_MODELER_CLUSTERS_0_URL_TASKLIST: https://${HOSTNAME}/tasklist # Updated for HTTPS
    # extra cluster configuration depending on the authentication mode
    env_file: ./.web-modeler/cluster-config-authentication-mode-${ZEEBE_AUTHENTICATION_MODE}.env
    networks:
      - web-modeler
      - camunda-platform

  web-modeler-webapp:
    container_name: web-modeler-webapp
    image: camunda/web-modeler-webapp:${CAMUNDA_WEB_MODELER_VERSION}
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 400M
          cpus: '0.3'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.modeler-webapp.rule=Host(`${HOSTNAME}`) && PathPrefix(`/modeler`)"
      - "traefik.http.routers.modeler-webapp.entrypoints=websecure"
      - "traefik.http.routers.modeler-webapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.modeler-webapp.loadbalancer.server.port=8070"
      - "traefik.http.middlewares.modeler-webapp-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.modeler-webapp-headers.headers.customrequestheaders.X-Forwarded-Host=${HOSTNAME}"
      - "traefik.http.routers.modeler-webapp.middlewares=modeler-webapp-headers"
    depends_on:
      web-modeler-restapi:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8071/health/readiness"]
      interval: 5s
      timeout: 15s
      retries: 30
    environment:
      RESTAPI_HOST: web-modeler-restapi
      SERVER_HTTPS_ONLY: "false"
      SERVER_URL: https://${HOSTNAME}/modeler # Updated for HTTPS
      PUSHER_APP_ID: web-modeler-app
      PUSHER_KEY: web-modeler-app-key
      PUSHER_SECRET: web-modeler-app-secret
      PUSHER_HOST: web-modeler-websockets
      PUSHER_PORT: "8060"
      CLIENT_PUSHER_HOST: ${HOSTNAME}
      CLIENT_PUSHER_PORT: "443" # Updated for HTTPS
      CLIENT_PUSHER_FORCE_TLS: "true" # Updated for HTTPS
      CLIENT_PUSHER_KEY: web-modeler-app-key
      OAUTH2_CLIENT_ID: web-modeler
      OAUTH2_JWKS_URL: http://keycloak:18080/auth/realms/camunda-platform/protocol/openid-connect/certs # Internal URL, remains unchanged
      OAUTH2_TOKEN_AUDIENCE: web-modeler-api
      OAUTH2_TOKEN_ISSUER: https://${HOSTNAME}/auth/realms/camunda-platform # Updated for HTTPS
      IDENTITY_BASE_URL: https://${HOSTNAME}/identity/ # Updated for HTTPS
      PLAY_ENABLED: "true"
    networks:
      - web-modeler
      - camunda-platform

  web-modeler-websockets:
    container_name: web-modeler-websockets
    image: camunda/web-modeler-websockets:${CAMUNDA_WEB_MODELER_VERSION}
    deploy:
      resources:
        limits:
          memory: 600M
          cpus: '0.4'
        reservations:
          memory: 300M
          cpus: '0.2'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.modeler-websockets.rule=Host(`${HOSTNAME}`) && PathPrefix(`/modeler-ws`)"
      - "traefik.http.routers.modeler-websockets.entrypoints=websecure"
      - "traefik.http.routers.modeler-websockets.tls.certresolver=letsencrypt"
      - "traefik.http.services.modeler-websockets.loadbalancer.server.port=8060"
      - "traefik.http.middlewares.modeler-websockets-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.modeler-websockets-headers.headers.customrequestheaders.X-Forwarded-Host=${HOSTNAME}"
      - "traefik.http.routers.modeler-websockets.middlewares=modeler-websockets-headers"
      # WebSocket upgrade headers
      - "traefik.http.middlewares.modeler-websockets-upgrade.headers.customrequestheaders.Upgrade=${http.request.header.Upgrade}"
      - "traefik.http.middlewares.modeler-websockets-upgrade.headers.customrequestheaders.Connection=${http.request.header.Connection}"
      - "traefik.http.routers.modeler-websockets.middlewares=modeler-websockets-headers,modeler-websockets-upgrade"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8060/up"]
      interval: 5s
      timeout: 15s
      retries: 30
    environment:
      APP_NAME: "Web Modeler Self-Managed WebSockets"
      APP_DEBUG: "true"
      PUSHER_APP_ID: web-modeler-app
      PUSHER_APP_KEY: web-modeler-app-key
      PUSHER_APP_SECRET: web-modeler-app-secret
    networks:
      - web-modeler

volumes:
  postgres-web:

networks:
  camunda-platform:
  web-modeler: 