#
# ident "@(#)$Id: docker-compose.yml | Sat Nov 18 22:55:23 2023 +0100 | UnknownUser @ MacBook-Air-GS-6.local  $"
# $Author: UnknownUser @ MacBook-Air-GS-6.local <UnknownUser@h-ka.de> $
#
# Copyright 2023-2024 (c) Guenther Schreiner <guenther.schreiner@smile.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# Description:
#      Definition of a standalone KeyCloak virtual machine
#
# Configuration:
#      All variables within this file have to be defined within
#       the file .env, which is linked into ./configuration/build.env
#       or a customized file ./configuration/build_local_$HOSTNAME.env
#       which is activated by using the command:
#           docker compose --env-file ./configuration/build_local_$HOSTNAME.env 
#
services:
  #
######################################################################################################################################################
  #
  # KeyCloak
  #
  keycloak:
    #
    # based on separate docker file
    #
    build:
      dockerfile:   	Dockerfile.keycloak
      context:      	.
      args:
         NOTE_THIS_IS_DEFINED_IN_DOCKERCOMPOSE: DOCKERCOMPOSE
    #
    # Runtime secrets for this container
    #
    secrets:
      - KC_HOSTNAME_FILE
      - KEYCLOAK_ADMIN_FILE
      - KEYCLOAK_ADMIN_PASSWORD_FILE
      - KC_DB_USERNAME_FILE
      - KC_DB_PASSWORD_FILE
      - KC_HTTPS_CERTIFICATE_FILE
      - KC_HTTPS_CERTIFICATE_KEY_FILE
      - keycloak_conf
    #
    # Gitlab Container Registry
    #
    image:		gitlab.smile.de:5050/group-hka/docker.keycloak
    #
    # Runtime execution environment from file
    #
    env_file:
      - configuration/runtime.env
      - configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}.env
    #
    # Runtime execution environment enhanced by some entries
    #
    environment:
      #
      # Defaults passed during build from build.env into environment
      #  optionally overridden by configuration/runtime*.env
      #
      HTTP_PROXY:       ${RUNTIME_HTTP_PROXY:-}
      HTTPS_PROXY:      ${RUNTIME_HTTPS_PROXY:-}
      no_proxy:		localhost
      #
      # Keycloak variable to use PostGreSQL
      #
      KC_DB:		postgres
      KC_DB_URL_HOST:	kc_postgres
      #
      # Keycloak script variable to start in development mode.
      #
      KEYCLOAK_DEVMODE: ${KEYCLOAK_DEVMODE:-}
      #
    #
    # Unique name for exact one instance
    #
    container_name:	keycloak${RELEASE:-}
    #
    # based on separate service
    #
    depends_on:
      - postgres${RELEASE:-}
    #
    # always running
    #
    restart:		unless-stopped
    #
    # with undelayed shutdown for writing dynamic files
    #
    stop_grace_period:	0s
    #
    # Exposed ports
    #
    ports:
      - ${DOCKER_PORT_KEYCLOAK_HTTP:-8080}:8080/tcp
      - ${DOCKER_PORT_KEYCLOAK_HTTPS:-8443}:8443/tcp
    #
    # Volumes with locally provided configuration
    # and data storage area
    # and database connectivity
    #
    volumes:
      - ./container.keycloak:/container:ro
      - ./container.keycloak/rw:/container/rw
    #
    # Networks
    #
    networks:
      - frontend
      - backend
    #
    # Host as upstream contact point
    #
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #
    # Metadata for this container
    #
    labels:
      de.smile.container.id:                    "@(#)$$Id: docker-compose.yml | Sat Nov 18 22:55:23 2023 +0100 | UnknownUser @ MacBook-Air-GS-6.local  $"
      de.smile.container.repo:                  "git@gitlab.smile.de:Group-HKA/docker.keycloak.git"
      de.smile.container.tier:                  frontend
      de.smile.container.network.providing:     8080/tcp@frontend
      de.smile.container.network.consuming:     N/A
  #
######################################################################################################################################################
  #
  # PostgreSQL
  #
  postgres:
    #
    # based on separate docker file
    #
    build:
      dockerfile:   Dockerfile.postgres
      context:      .
      args:
         NOTE_THIS_IS_DEFINED_IN_DOCKERCOMPOSE: DOCKERCOMPOSE
    #
    # Runtime secrets for this container
    #
    secrets:
      - POSTGRES_DB_FILE
      - POSTGRES_USER_FILE
      - POSTGRES_PASSWORD_FILE
      - POSTGRES_INITDB_ARGS_FILE
    #
    # Gitlab Container Registry
    #
    image:              gitlab.smile.de:5050/group-hka/docker.keycloak.postgres
    #
    # Runtime execution environment from file
    #
    env_file:
      - configuration/runtime.env
      - configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}.env
    #
    # Runtime execution environment enhanced by some entries
    #
    environment:
      #
      # Defaults passed during build from build.env into environment
      #  optionally overridden by configuration/runtime*.env
      #
      HTTP_PROXY:       ${RUNTIME_HTTP_PROXY:-}
      HTTPS_PROXY:      ${RUNTIME_HTTPS_PROXY:-}
      no_proxy:		localhost
      #
    #
    # Unique name for exact one instance
    #
    container_name:	kc_postgres${RELEASE:-}
    #
    # always running
    #
    restart:		unless-stopped
    #
    # with delayed shutdown for writing dynamic files
    #
    stop_grace_period: 10s
    #
    # Exposed ports: none
    #
    # Volumes with locally provided configuration
    # and locally provided database storage area
    #
    volumes:
      - ./container.postgres:/container:ro
      - ./container.postgres/rw:/container/rw
      - ./container.postgres/postgres-data:/var/lib/postgresql/data/
    #
    # Networks (backend only)
    #
    networks:
      - backend
    #
    # Host as upstream contact point
    #
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #
    # Metadata for this container
    #
    labels:
      de.smile.container.id:                    "@(#)$$Id: docker-compose.yml | Sat Nov 18 22:55:23 2023 +0100 | UnknownUser @ MacBook-Air-GS-6.local  $"
      de.smile.container.repo:                  "git@gitlab.smile.de:Group-HKA/docker.keycloak.postgres.git"
      de.smile.container.tier:                  backend
      de.smile.container.network.providing:     5432@backend
      de.smile.container.network.consuming:     none
  #
######################################################################################################################################################
  #
  # adminer - Database management in a single PHP file.
  #
  adminer:
    #
    # based on an Docker image
    #
    image:		adminer
    #
    # Gitlab Container Registry
    #
    #image:              gitlab.smile.de:5050/group-hka/docker.keycloak.adminer
    #
    # Runtime execution environment from file
    #
    env_file:
      - configuration/runtime.env
      - configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}.env
    #
    # Runtime execution environment enhanced by some entries
    #
    environment:
      #
      # Defaults passed during build from build.env into environment
      #  optionally overridden by configuration/runtime*.env
      #
      HTTP_PROXY:       ${RUNTIME_HTTP_PROXY:-}
      HTTPS_PROXY:      ${RUNTIME_HTTPS_PROXY:-}
      no_proxy:		localhost
      KEYCLOAK_DEVMODE: ${KEYCLOAK_DEVMODE:-}
      #
    #
    # Unique name for exact one instance
    #
    container_name: 	adminer${RELEASE:-}
    #
    # based on separate service
    #
    depends_on:
      - postgres${RELEASE:-}
    #
    # Optional service: started only with profile debug
    #
    profiles:
      - debug
    #
    # always running
    #
    restart:		unless-stopped
    #
    # Exposed ports
    #
    ports:
      - ${DOCKER_PORT_ADMINER_HTTP:-8081}:8080/tcp
    #
    # Networks (backend only)
    #
    networks:
      - backend
    #
    # Host as upstream contact point
    #
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #
    # Metadata for this container
    #
    labels:
      de.smile.container.id:                    "@(#)$$Id: docker-compose.yml | Sat Nov 18 22:55:23 2023 +0100 | UnknownUser @ MacBook-Air-GS-6.local  $"
      de.smile.container.repo:                  "git@gitlab.smile.de:Group-HKA/docker.keycloak.adminer.git"
      de.smile.container.tier:                  backend
      de.smile.container.network.providing:     8080@backend
      de.smile.container.network.consuming:     none
  #
######################################################################################################################################################
# All Runtime secrets
#
secrets:
  #
  # Keycloak specific
  #
  KC_HOSTNAME_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/kc_hostname.txt
  KEYCLOAK_ADMIN_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/kc_admin_user.txt
  KEYCLOAK_ADMIN_PASSWORD_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/kc_admin_password.txt
  KC_DB_USERNAME_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/postgres_user.txt
  KC_DB_PASSWORD_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/postgres_password.txt
  KC_HTTPS_CERTIFICATE_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/kc_cert.pem
  KC_HTTPS_CERTIFICATE_KEY_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/kc_key.pem
  keycloak_conf:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/keycloak.conf
  #
  # Postgres specific
  #
  POSTGRES_DB_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/postgres_db.txt
  POSTGRES_USER_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/postgres_user.txt
  POSTGRES_PASSWORD_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/postgres_password.txt
  POSTGRES_INITDB_ARGS_FILE:
    file:		./configuration/runtime_local_${HOSTNAME:-SAMPLEHOST}/postgres_initdb_args.txt
#
######################################################################################################################################################
##
## Networks as separate infrastructure
##
networks:
  ##
  ## Frontend service (provided by some containers)
  ##
  frontend:
    #
    # Initialized elsewhere
    #
    name:       ${DOCKER_NETWORK_FRONTEND:-frontend}
    #
    # Initialized elsewhere
    #
    external:   true
    #
  ##
  ## Backend service (provided by some containers)
  ##
  backend:
    #
    # Initialized elsewhere
    #
    name:       ${DOCKER_NETWORK_BACKEND:-backend}
    #
    # Initialized elsewhere
    #
    external:   true
    #
#
# end-of-docker-compose.yml
#
