#!/bin/sh
#
# ident "@(#)$Id: __-Docker_secret_helper | Sat Nov 18 22:55:00 2023 +0100 | UnknownUser @ MacBook-Air-GS-6.local  $"
# $Author: UnknownUser @ MacBook-Air-GS-6.local <UnknownUser@h-ka.de> $
#
# Copyright 2023 (c) Guenther Schreiner <guenther.schreiner@smile.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# Description:
#      Helper script to overcome bogus docker secret handling.
#
# Configuration:
#       @see Constants
#
# 
###
### Main
###
#
# Determine how this script is executed
#  (see http://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced)
#
if [ "$0" = "$BASH_SOURCE" ]; then
   sourced=0
else
   sourced=1
fi
#
# Abort if this script is not sourced
#
if [ $sourced -eq 0 ]; then
   echo " "
   echo "ERROR: to use this helper, you have to source this script, i.e. with"
   echo " "
   echo " . $0"
   echo " "
   exit 1
fi
#
# Overcome bogus environment handling
#
export KC_HOSTNAME=$(cat $KC_HOSTNAME_FILE)
export KEYCLOAK_ADMIN=$(cat $KEYCLOAK_ADMIN_FILE)
export KEYCLOAK_ADMIN_PASSWORD=$(cat $KEYCLOAK_ADMIN_PASSWORD_FILE)
export KC_DB_USERNAME=$(cat $KC_DB_USERNAME_FILE)
export KC_DB_PASSWORD=$(cat $KC_DB_PASSWORD_FILE)
#
# end-of-__-Docker_secret_helper
#
